### ISSUE TITLE
Allow f7Tabs to be hidden

### ISSUE THREAD

**Issue by rodrigoheck** [RinteRface/shinyMobile#44] opened 2019-12-27 03:50 UTC
I was trying to create sub-tabs that could be accessed using updateF7Tabs and a button, but I've been failing to do that without creating another icon in the toolbar on the bottom. It would be a nice enhancement to be able to create these "hidden" tabs. Amazing library, by the way. :)

**Comment by DivadNojnarg** [comment] 2020-01-05 15:34
Hi Rodrigo, Could you provide a reproducible code? Thanks

**Comment by rodrigoheck** [comment] 2020-01-08 00:48
Sure. Here it is:

`shinyApp(
  ui <- f7Page(
  title = "shinyMobile",
  init = f7Init(
    skin = "auto",
    theme = "light",
    color = 'blue',
    filled = TRUE,
    hideNavOnPageScroll = FALSE,
    hideTabsOnPageScroll = FALSE,
    serviceWorker = "service-worker.js"
  ),
  f7TabLayout(
    navbar = f7Navbar(
      title = "App name",
      subtitle = "",
      hairline = TRUE,
      shadow = TRUE,
      left_panel = TRUE,
      right_panel = FALSE,
      bigger = FALSE,
      transparent = TRUE
    ), 
    f7Tabs(id = 'tabs',
           animated = TRUE,
           f7Tab(tabName = 'Main tab', icon = f7Icon('document_text'),
                 h1("This is a tab"), 
                 f7Button(inputId='goto', label = 'Go to hidden tab')
           ),
           f7Tab(tabName = 'Second tab',
                 icon = f7Icon('bolt_horizontal'),
                 h1('This is a tab') 
           ),
           f7Tab(tabName = 'Hidden tab',
                 h1('This is a tab that should be hidden')
           )
))
),

server = function(input, output, session) {
  
  observeEvent(input$goto,{
    updateF7Tabs(session = session, id = 'tabs', selected = 'Hidden tab')
  })
  
}
)
`

**Comment by DivadNojnarg** [comment] 2020-01-08 07:51
You could do like this:

- add hidden parameter to the f7Tab function and store it in a data attribute:

```r
f7Tab <- function(..., tabName, icon = NULL, active = FALSE, hidden = FALSE) {
  
  id <- tabName
  # handle punctuation
  id <- gsub(x = id, pattern = "[[:punct:]]", replacement = "")
  # handle tab names with space
  id <- gsub(x = id, pattern = " ", replacement = "")
  
  itemTag <- shiny::tags$div(
    class = if (!active) "page-content tab" else "page-content tab tab-active",
    `data-active` = tolower(active),
    id = id,
    `data-value` = tabName,
    `data-hidden` = hidden,
    style = "background-color: gainsboro;",
    ...
  )
  return(list(itemTag, icon, tabName))
}
```

- While generating item menu in the f7Tabs function, if the item has the hidden attribute TRUE, do not generate the corresponding link in the bottom bar:

```r
f7Tabs <- function(..., .items = NULL, id = NULL, swipeable = FALSE, animated = TRUE) {
  
  if (swipeable && animated) stop("Cannot use two effects at the same time")
  if (is.null(id)) id <- paste0("tabs_", round(stats::runif(1, min = 0, max = 1e9)))
  
  toolbarItems <- list(...)
  len <- length(toolbarItems)
  found_active <- FALSE
  
  # toolbar items
  toolbarTag <- f7Toolbar(
    position = "bottom",
    hairline = TRUE,
    shadow = TRUE,
    icons = TRUE,
    scrollable = FALSE,
    lapply(1:len, FUN = function(i) {
      
      item <- toolbarItems[[i]][[1]]
      itemIcon <- toolbarItems[[i]][[2]]
      itemName <- toolbarItems[[i]][[3]]
      itemClass <- item$attribs$class
      itemId <- item$attribs$id
      itemHidden <- item$attribs$`data-hidden`
      
      # make sure that if the user set 2 tabs active at the same time,
      # only the first one is selected
      if (!found_active) {
        active <- sum(grep(x = itemClass, pattern = "active")) == 1
        if (active) found_active <<- TRUE
        # if there is already an active panel, set all other to inactive
      } else {
        active <- FALSE
      }
      
      # generate the link
      if (!itemHidden) {
        if (!is.null(itemIcon)) {
          shiny::a(
            href = paste0("#", itemId),
            class = if (active) "tab-link tab-link-active" else "tab-link",
            itemIcon,
            shiny::span(class = "tabbar-label", itemName)
          )
        } else {
          shiny::a(
            href = paste0("#", itemId),
            class = if (active) "tab-link tab-link-active" else "tab-link",
            itemName,
          )
        } 
      }
    }),
    .items
  )
  
  # related page content
  contentTag <- shiny::tags$div(
    # ios-edges necessary to have
    # the good ios rendering
    class = "tabs ios-edges",
    lapply(1:len, function(i) { toolbarItems[[i]][[1]]})
  )
  
  contentTag$attribs$id <- id
  
  # handle swipeable tabs
  if (swipeable) {
    contentTag <- shiny::tags$div(
      class = "tabs-swipeable-wrap",
      contentTag
    )
  }
  
  if (animated) {
    contentTag <- shiny::tags$div(
      class = "tabs-animated-wrap",
      contentTag
    )
  }
  
  shiny::tagList(shinyMobile:::f7InputsDeps(), toolbarTag, contentTag)
  
}
```

See this line `if (!itemHidden) {...}`...

This way, the third tab does not display in the navigation bar. When clicking on the go button, you will be moving to this tab. 

Alternatively, you could also proceed like this in the f7Tabs (add a display none style to the hidden tab):

```r
if (!is.null(itemIcon)) {
          shiny::a(
            href = paste0("#", itemId),
            class = if (active) "tab-link tab-link-active" else "tab-link",
            itemIcon,
            shiny::span(class = "tabbar-label", itemName),
            style = if (itemHidden) "display: none;" else NULL
          )
        } else {
          shiny::a(
            href = paste0("#", itemId),
            class = if (active) "tab-link tab-link-active" else "tab-link",
            itemName,
            style = if (itemHidden) "display: none;" else NULL
          )
        } 
```

You will notice however that the tab menu does not update properly. In the first case, when click on go, even though we navigate to the third tab, tab 1 still appear selected. In the second case, the number of items is wrong. This is because more work needs to be done on the JavaScript side.

I will let you know when it is ready. Thanks for the suggestion

**Closed** 2020-01-08 09:19 UTC
